### ISSUE TITLE
spi.h needs commenting in our style

### ISSUE THREAD

**Issue by wittsend** [AdamParlane/aut-swarm-robotics#12]

**Comment by AdamParlane** [comment]
This is a default library for the SAM4N8C, i dont think we should waste our time with this. This single line that is changed (fixed) is well documented in opt_interface.c

**Comment by wittsend** [comment]
Yeah, but it would be nice if it had the same header as the other files. I'll keep it as a low priority though.

**Comment by wittsend** [comment]
Added our own header (and retained copyright notice and disclaimer as required by Atmel)
