### ISSUE TITLE
Positional Data Layout

### ISSUE THREAD

**Issue by wittsend** [AdamParlane/aut-swarm-robotics#134]
I think that the dx, dy and x, y variables for the optical sensor should be raw count values from the sensors. (no resolution calibration performed). The calibration should occur when moving this data from the raw variables to the pos.x and pos.y, pos.speed variables which will all contain real world figures. This way, you can separate the function that retrieves the data from the sensors from the function that converts the data to useful information (hence making code more modular)

Integers (counts)
pos.optical.dx
pos.optical.dy
pos.optical.x
pos.optical.y

floats (mm)
pos.x
pos.y
pos.dx
pos.dy
pos.speed

In addition: (floats)
pos.heading: Direction robot is moving relative to the front of robot (ie take from the mouse)
pos.facing: Absolute direction the robot is facing, taken from the IMU and webcam

**Comment by AdamParlane** [comment]
Agreed, I will try resolve today
