### ISSUE TITLE
Test Functions need testing on Robot

### ISSUE THREAD

**Issue by AdamParlane** [AdamParlane/aut-swarm-robotics#16]
Im sure there will be at least a couple logic erros that need to be ironed out with testing on the actual robot

**Comment by AdamParlane** [comment]
Testing going well, need more work on Mansel's end to determine if every works as it should

**Comment by wittsend** [comment]
Are the test functions all working now?

**Comment by MJeffares** [comment]
They were working before the break but we tested them last week 12/09/17 and something wasn't working, believed to be robot sided. Hope to test this tomorrow after our meeting?

**Comment by AdamParlane** [comment]
All working as per yesterdays testing
