### ISSUE TITLE
motor_driver needs updating to new formatting style and headers

### ISSUE THREAD

**Issue by wittsend** [AdamParlane/aut-swarm-robotics#24]

**Comment by wittsend** [comment]
Mostly done, just needs implementation descriptions. Might be best if you did this @AdamParlane

**Comment by AdamParlane** [comment]
yeah, absolutely, ill try do before we meet Mark tomorrow

**Comment by wittsend** [comment]
Thanks Adam

**Comment by AdamParlane** [comment]
All done :)
