### ISSUE TITLE
Why does RXRDY for TWI0 need to be cleared at setup time?

### ISSUE THREAD

**Issue by wittsend** [AdamParlane/aut-swarm-robotics#8]
Was browsing the code and noticed that there is a line that loads a "dummy" value into the receive hold register for TWI0 after setup. What is this for?
`uint8_t dummy = REG_TWI0_RHR;			//Ensure RXRDY flag is cleared`
this is in `twi0Init()`

Just curious...

**Comment by AdamParlane** [comment]
Not 100% sure, thats more of an Esmond / Jake question (not sure which one wrote it), but I just presumed you had to clear it to get going, im guessing though

**Comment by wittsend** [comment]
Haven't seen this in any example code. Will ask Esmond when I see him.

**Comment by EsMather** [comment]
Hey,
It was just used when we were troubleshooting the TWI. You could delete that line. I'm sure it will still work without it.

**Comment by wittsend** [comment]
OK thanks Es
